#include<iostream>
using namespace std;
int main(){
    int a=10;
    int b=0;
    cout<<"Before divide"<<endl;
    int c=a/b;  //When some part of code makes the program terminate abnormally then this is called as exception
    cout<<"After divide"<<endl;
    cout<<"Exception Occured"<<endl;
}